general {
    lock_cmd = pidof hyprlock || hyprlock
}

# Lock the screen
listener {
    timeout = 180
    on-timeout = ~/.config/hypr/scripts/powermenu.sh Lock
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# # Suspend the system
# listener {
#     timeout = 330
#     on-timeout = systemctl suspend
# }
