general {
    lock_cmd = pidof hyprlock || hyprlock
}

# Lock the screen
listener {
    timeout = 300
    on-timeout = bash ~/.config/quickshell/src/services/launcher/launcher.sh provider power Lock
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# # Suspend the system
# listener {
#     timeout = 330
#     on-timeout = systemctl suspend
# }
