source = ~/.config/hypr/config.d/environmentvariables.conf
#remove this line if you dont need private env variables
source = ~/.config/hypr/config.d/environmentvariables.private.conf
source = ~/.config/hypr/config.d/monitors.conf
source = ~/.config/hypr/config.d/autostart.conf
source = ~/.config/hypr/config.d/keybindings.conf
source = ~/.config/hypr/config.d/submaps.conf
source = ~/.config/hypr/config.d/windowrules.conf

source = ~/.config/hypr/themes/mocha.conf
# See https://wiki.hyprland.org

ecosystem {
    no_donation_nag = true
}

input {
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options =
    kb_rules =
    force_no_accel = true
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

misc {
    disable_hyprland_logo = true
    background_color = $inactiveColor
}

general {
    
    gaps_in = 1
    gaps_out = 0
    border_size = 2

    col.active_border = rgb(6272a4)
    col.inactive_border = $inactiveColor
    layout = dwindle
}

group {
    groupbar {
        enabled = false
        font_family = "JetBrainsMono Nerd Font", sans-serif;
        font_weight_active = bold
        font_weight_inactive = semibold
        col.active = rgb(6272a4)
        col.inactive = $inactiveColor
        col.locked_active = $inactiveColor
        col.locked_inactive = $inactiveColor
        indicator_gap = 0
        indicator_height = 0
        font_size = 14
        render_titles = true
        keep_upper_gap = true
        gaps_out = 0
        gaps_in = 0
        stacked = false
        gradients = true
        text_color = $inactiveColor
        text_color_inactive = $text
    }
    col.border_active = rgb(6272a4)
    col.border_inactive = $inactiveColor
    col.border_locked_active = $inactiveColor
    col.border_locked_inactive = $inactiveColor
    insert_after_current = false
}


decoration {
    rounding = 0
    blur { 
        enabled=false
    }
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 2, myBezier
    animation = windowsOut, 1, 2, default, popin 80%
    animation = border, 1, 2, default
    animation = borderangle, 1, 2, default
    animation = fade, 1, 2, default
    animation = workspaces, 1, 2, default
}

dwindle {
    pseudotile = yes 
    preserve_split = yes
	force_split = 2
}

master {
    #new_is_master = true
}

# gestures {
#     workspace_swipe = off
# }

# cursor {
#   no_hardware_cursors = true
# }
