local home = os.getenv("HOME")
local scripts = home .. "/.config/hypr/scripts"

hl.define_submap("resize", function()
    hl.bind("l", hl.dsp.window.resize({ x = 10,  y = 0,   relative = true}), { repeating = true, desc = "right" })
    hl.bind("h", hl.dsp.window.resize({ x = -10, y = 0,   relative = true}), { repeating = true, desc = "left" })
    hl.bind("k", hl.dsp.window.resize({ x = 0,   y = 10,  relative = true}), { repeating = true, desc = "down" })
    hl.bind("j", hl.dsp.window.resize({ x = 0,   y = -10, relative = true}), { repeating = true, desc = "up" })

    hl.bind("escape",   hl.dsp.submap("reset"))
    hl.bind("catchall", hl.dsp.submap("reset"))
end)


hl.define_submap("notes", "reset", function()
    hl.bind("t", hl.dsp.exec_cmd(scripts .. "/floating-notes.sh random"),   { desc = "random temporary note" })
    hl.bind("w", hl.dsp.exec_cmd(scripts .. "/floating-notes.sh work"),     { desc = "open work notes" })
    hl.bind("p", hl.dsp.exec_cmd(scripts .. "/floating-notes.sh personal"), { desc = "open personal notes" })

    hl.bind("escape",   hl.dsp.submap("reset"))
    hl.bind("catchall", hl.dsp.submap("reset"))
end)

hl.define_submap("tools", "reset", function()
    hl.bind("c", hl.dsp.exec_cmd(scripts .. "/tools/colour-picker.sh"),     { desc = "color picker" })
    hl.bind("b", hl.dsp.exec_cmd('ghostty -e btop'),   { desc = "system monitor" })
    hl.bind("d", hl.dsp.exec_cmd(scripts .. "/tools/currentdate.sh"),     { desc = "current date" })
    hl.bind("e", hl.dsp.exec_cmd(scripts .. "/tools/encode-qrcode.sh"),   { desc = "encode qrcode" })
    hl.bind("f", hl.dsp.exec_cmd('ghostty -e ncdu --group-directories-first'),{ desc = "disk usage" })
    hl.bind("g", hl.dsp.exec_cmd(scripts .. "/tools/uuidgen.sh"),         { desc = "generate uuid" })
    hl.bind("m", hl.dsp.exec_cmd('ghostty --title="musicplayer" -e rmpc'),{ desc = "music player" })
    hl.bind("n", hl.dsp.exec_cmd(scripts .. "/tools/ptvatid/create.sh"),  { desc = "create PT VAT id" })
    hl.bind("o", hl.dsp.exec_cmd(scripts .. "/screen/shot.sh ocr"),       { desc = "ocr from screen region" })
    hl.bind("p", hl.dsp.window.pin(),                                     { desc = "pin active window" })
    hl.bind("q", hl.dsp.exec_cmd(scripts .. "/screen/shot.sh qrcode"),    { desc = "qrcode from screen region" })
    hl.bind("u", hl.dsp.exec_cmd("uxplay"),                               { desc = "share iPhone screen" })
    hl.bind("w", hl.dsp.exec_cmd('ghostty --title="wallpapers" -e sh -c \'' .. scripts .. '/wallpapers/picker.sh "' .. home .. '/Pictures/wallpapers/"\''), { desc = "wallpaper picker" })
    hl.bind("escape",   hl.dsp.submap("reset"))
    hl.bind("catchall", hl.dsp.submap("reset"))
end)