exec-once = systemctl --user start hyprpolkitagent

exec-once = hypridle
exec-once = pcmanfm-qt -d
exec-once = swww-daemon
exec-once = waybar
exec-once = ~/.config/hypr/scripts/wallpapers/default.sh
exec-once = swaync
exec-once = copyq --start-server

exec-once = solaar --window=hide
exec-once = udiskie --no-automount --tray
exec-once = nm-applet
exec-once = firewall-applet
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprctl dispatch workspace 1
exec-once = socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock EXEC:"$HOME/.config/hypr/events/shellevents $HOME/.config/hypr/events/shellevents_handlers",nofork

