exec-once = systemctl --user start hyprpolkitagent

# exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = hypridle
exec-once = pcmanfm-qt -d
exec-once = pypr
# exec-once = hyprpaper
exec-once = swww-daemon
exec-once = waybar
exec-once = ~/Projects/scripts/utils/hyprland/wallpapers/default.sh
exec-once = swaync
# exec-once = swaync-client --change-noti-monitor HDMI-A-1
exec-once = copyq --start-server

exec-once = ~/Projects/scripts/utils/clipboard/monitor-vm.sh
exec-once = ~/Projects/scripts/utils/hyprland/notifications/handler.sh

# exec-once = ~/Projects/scripts/utils/conky/start.sh
# exec-once = steam -silent
exec-once = ~/Projects/scripts/utils/browser/pdf2png.sh
# exec-once = streamdeck -n
# exec-once = streamcontroller -b # launched by the shellevents script
exec-once = solaar --window=hide
exec-once = udiskie --no-automount --tray
exec-once = nm-applet
exec-once = firewall-applet
# exec-once = keepassxc --minimized
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = hyprctl dispatch workspace 1

exec-once = socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock EXEC:"$HOME/.config/hypr/scripts/shellevents $HOME/.config/hypr/scripts/shellevents_handlers",nofork

