# mouse cursor

env = XCURSOR_THEME,Breeze_Light
env = XCURSOR_SIZE,24

# nvidia

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# path 
env = PATH, /bin:/usr/bin:/usr/local/bin:$HOME/.local/bin

# https://github.com/ghostty-org/ghostty/discussions/8899
env = GTK_IM_MODULE,simple
