submap = notes, reset # automatically exits after picking an option
    bind = , N,  exec, $scripts/floating-notes.sh random
    bind = , W,  exec, $scripts/floating-notes.sh work
    bind = , P,  exec, $scripts/floating-notes.sh personal
    bind = , escape, submap, reset
    bind = , catchall, submap, reset
submap = reset

submap = resize
    binde = , right, resizeactive, 50 0
    binde = , left, resizeactive, -50 0
    binde = , up, resizeactive, 0 -50
    binde = , down, resizeactive, 0 50

    binde = , l, resizeactive, 50 0
    binde = , h, resizeactive, -50 0
    binde = , k, resizeactive, 0 -50
    binde = , j, resizeactive, 0 50

    bind = , escape, submap, reset
    bind = , catchall, submap, reset
submap = reset