submap = notes, reset # automatically exits after picking an option
    bind = , N,  exec, $scripts/floating-notes.sh random
    bind = , W,  exec, $scripts/floating-notes.sh work
    bind = , P,  exec, $scripts/floating-notes.sh personal
    bind = , escape, submap, reset
    bind = , catchall, submap, reset
submap = reset

submap = resize
    binde = , right, resizeactive, 50 0
    binde = , left, resizeactive, -50 0
    binde = , up, resizeactive, 0 -50
    binde = , down, resizeactive, 0 50

    binde = , l, resizeactive, 50 0
    binde = , h, resizeactive, -50 0
    binde = , k, resizeactive, 0 -50
    binde = , j, resizeactive, 0 50

    bind = , escape, submap, reset
    bind = , catchall, submap, reset
submap = reset

submap = tools, reset
    bind = , c, exec, hyprpicker -an
    bind = , d, exec, $scripts/tools/currentdate.sh
    bind = , e, exec, $scripts/tools/encode-qrcode.sh
    bind = , g, exec, $scripts/tools/uuidgen.sh
    bind = , n, exec, $scripts/tools/ptvatid/create.sh
    bind = , o, exec, $scripts/screen/shot.sh ocr
    bind = , q, exec, $scripts/screen/shot.sh qrcode
    bind = , u, exec, $waybar/uxplay toggle
    bind = , w, exec, $waybar/win11 toggle
    bind = , escape, submap, reset
    bind = , catchall, submap, reset
submap = reset